workflows:
  android_guardian_aab:
    name: guardian-android-aab
    max_build_duration: 120
    environment:
      node: 20.19.4
      java: 17
      vars:
        APP_DIR: .
        NODE_ENV: "production"
        # Public app config (keep builds deterministic even if Codemagic UI vars are missing)
        EXPO_PUBLIC_API_URL: "http://api.dongdong.io:3000/api/v1"
        EXPO_PUBLIC_WEBVIEW_URL: "https://guardian.dongdong.kr"
        EXPO_PUBLIC_KAKAO_APP_KEY: "47bc9c4a41a6efc98804915332fbc7e8"
        KAKAO_APP_KEY: "47bc9c4a41a6efc98804915332fbc7e8"
        # Secrets must be set in Codemagic UI (Environment variables / Groups):
        # - CM_KEYSTORE_PASSWORD
        # - CM_KEY_PASSWORD   (if different from store password)
        # Secure file upload (keystore): upload as `upload.jks` (or change KEYSTORE_FILE below).
        KEYSTORE_FILE: upload.jks
    scripts:
      - name: Install dependencies (npm ci)
        script: |
          cd "$APP_DIR"
          npm ci
      - name: Expo prebuild (android)
        script: |
          cd "$APP_DIR"
          rm -rf android ios
          npx expo prebuild --platform android --clean
      - name: Android bundleRelease (AAB)
        script: |
          cd "$APP_DIR/android"
          # Resolve keystore file path robustly (Codemagic can expose it via different mechanisms).
          KEYSTORE_PATH=""

          # 1) Codemagic Android keystore integration (preferred)
          if [ -n "${CM_KEYSTORE_PATH:-}" ] && [ -f "${CM_KEYSTORE_PATH:-}" ]; then
            KEYSTORE_PATH="${CM_KEYSTORE_PATH:-}"
          fi

          # 2) Secure files
          if [ -z "$KEYSTORE_PATH" ] && [ -n "${CM_SECURE_FILES_PATH:-}" ] && [ -f "${CM_SECURE_FILES_PATH:-}/$KEYSTORE_FILE" ]; then
            KEYSTORE_PATH="${CM_SECURE_FILES_PATH:-}/$KEYSTORE_FILE"
          fi

          # 3) Build dir (if user uploaded as a generic file)
          if [ -z "$KEYSTORE_PATH" ] && [ -f "$CM_BUILD_DIR/$KEYSTORE_FILE" ]; then
            KEYSTORE_PATH="$CM_BUILD_DIR/$KEYSTORE_FILE"
          fi

          # 4) Fallback: find any .jks under secure files / home
          if [ -z "$KEYSTORE_PATH" ] && [ -n "${CM_SECURE_FILES_PATH:-}" ] && [ -d "${CM_SECURE_FILES_PATH:-}" ]; then
            KEYSTORE_PATH="$(find "$CM_SECURE_FILES_PATH" -maxdepth 2 -type f -name '*.jks' 2>/dev/null | head -n 1 || true)"
          fi
          if [ -z "$KEYSTORE_PATH" ]; then
            KEYSTORE_PATH="$(find "$HOME" -maxdepth 5 -type f -name '*.jks' 2>/dev/null | head -n 1 || true)"
          fi

          test -n "$KEYSTORE_PATH" && test -f "$KEYSTORE_PATH" || (echo "Keystore file not found. Upload a .jks (Android keystore integration or Secure files) and ensure CM_KEYSTORE_PASSWORD is set." && exit 2)
          echo "KEYSTORE_PATH=$KEYSTORE_PATH"
          ls -la "$KEYSTORE_PATH" || true

          # Auto-detect alias to avoid manual mistakes (works when keystore has a single entry).
          KEY_ALIAS="${CM_KEY_ALIAS:-}"
          if [ -z "$KEY_ALIAS" ]; then
            KEY_ALIAS="$(keytool -list -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" 2>/dev/null | awk -F, 'NF>=1 {gsub(/^[ \t]+|[ \t]+$/, "", $1); if ($1!="") {print $1; exit}}')"
          fi
          test -n "$KEY_ALIAS" || (echo "Failed to detect key alias. Set CM_KEY_ALIAS explicitly." && exit 2)

          KEY_PASS="${CM_KEY_PASSWORD:-$CM_KEYSTORE_PASSWORD}"

          echo "=== SIGNING_INFO (guardian) ==="
          echo "package=$(node -e \"console.log(require('../app.json').expo.android.package)\")"
          echo "versionCode=$(node -e \"console.log(require('../app.json').expo.android.versionCode)\")"
          echo "KEY_ALIAS=$KEY_ALIAS"
          keytool -list -v -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" -alias "$KEY_ALIAS" 2>/dev/null | grep -E "SHA1:|SHA256:" || true
          if command -v openssl >/dev/null 2>&1; then
            KEY_HASH="$(keytool -exportcert -alias "$KEY_ALIAS" -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" 2>/dev/null | openssl sha1 -binary | openssl base64 2>/dev/null || true)"
            if [ -n "$KEY_HASH" ]; then
              echo "KAKAO_KEY_HASH=$KEY_HASH"
              echo "$KEY_HASH" > "$CM_BUILD_DIR/kakao_key_hash.txt"
            fi
          fi

          ./gradlew --no-daemon --max-workers=1 :app:bundleRelease \
            -Pandroid.injected.signing.store.file="$KEYSTORE_PATH" \
            -Pandroid.injected.signing.store.password="$CM_KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASS"
      - name: Verify + SHA256
        script: |
          cd "$APP_DIR/android"
          AAB="$(ls -1 app/build/outputs/bundle/release/*.aab | head -n 1 || true)"
          test -n "$AAB" || (echo "AAB not found" && exit 3)
          echo "AAB=$AAB"
          jarsigner -verify -verbose -certs "$AAB" || exit 4
          sha256sum "$AAB" | tee "$AAB.sha256.txt"
    artifacts:
      - kakao_key_hash.txt
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/bundle/release/*.sha256.txt
      - android/app/build/outputs/mapping/release/mapping.txt
      - android/app/build/reports/**/*

