workflows:
  android_guardian_aab:
    name: guardian-android-aab
    max_build_duration: 120
    environment:
      node: 20.19.4
      java: 17
      android_signing:
        # IMPORTANT:
        # Guardian Play Console expects a DIFFERENT upload certificate than caregiver.
        # If you sign guardian with the wrong keystore, Play will reject with:
        # "signed with the wrong key ... found SHA1=..., expected SHA1=..."
        - guardian-upload
      groups:
        - google_credentials
        - dev
      vars:
        APP_DIR: .
        NODE_ENV: "production"
        # Versioning (prevent Play upload failures due to non-increasing versionCode)
        VC_BASE: 200000
        # Public app config (keep builds deterministic even if Codemagic UI vars are missing)
        EXPO_PUBLIC_API_URL: "http://api.dongdong.io:3000/api/v1"
        EXPO_PUBLIC_WEBVIEW_URL: "https://guardian.dongdong.kr"
        EXPO_PUBLIC_KAKAO_APP_KEY: "47bc9c4a41a6efc98804915332fbc7e8"
        KAKAO_APP_KEY: "47bc9c4a41a6efc98804915332fbc7e8"
        # Secrets must be set in Codemagic UI (Environment variables / Groups):
        # - CM_KEYSTORE_PASSWORD
        # - CM_KEY_PASSWORD   (if different from store password)
        # Secure file upload (keystore): upload as `guardian-upload.jks` (recommended).
        KEYSTORE_FILE: guardian-upload.jks
        # Play Console expected upload cert SHA1 for guardian (from Play error message).
        # Used as a guard to fail fast if Codemagic picked the wrong keystore.
        EXPECTED_UPLOAD_CERT_SHA1: "75:69:F0:C6:EF:65:C2:8A:A9:04:40:41:D6:C6:08:0C:80:E6:FF:10"
    scripts:
      - name: Install dependencies (npm ci)
        script: |
          cd "$APP_DIR"
          # IMPORTANT:
          # NODE_ENV is set to "production" for Expo config stability, but we still need devDependencies
          # during bundling/prebuild.
          export npm_config_production=false
          npm ci
          node -e "require('./metro.config.js'); console.log('[ci] metro.config.js OK')" || exit 2
      - name: Set Android versionCode (CI monotonic)
        script: |
          cd "$APP_DIR"
          node -e "
            const fs=require('fs');
            const p='./app.json';
            const j=JSON.parse(fs.readFileSync(p,'utf8'));
            const base=Number(process.env.VC_BASE||200000);
            const n=Number(process.env.CM_BUILD_NUMBER||0);
            const vc=base + (Number.isFinite(n)&&n>0?n:1);
            j.expo=j.expo||{};
            j.expo.android=j.expo.android||{};
            j.expo.android.versionCode=vc;
            fs.writeFileSync(p, JSON.stringify(j,null,2)+'\\n');
            console.log('[ci] android.versionCode='+vc);
          "
      - name: Expo prebuild (android)
        script: |
          cd "$APP_DIR"
          rm -rf android ios
          npx expo prebuild --platform android --clean
      - name: Android bundleRelease (AAB)
        script: |
          cd "$APP_DIR/android"
          # Resolve keystore file path robustly (Codemagic can expose it via different mechanisms).
          KEYSTORE_PATH=""
          echo "KEYSTORE_FILE=${KEYSTORE_FILE:-}"
          echo "CM_KEYSTORE_PATH=${CM_KEYSTORE_PATH:-}"
          echo "CM_SECURE_FILES_PATH=${CM_SECURE_FILES_PATH:-}"
          echo "CM_BUILD_DIR=${CM_BUILD_DIR:-}"

          # 1) Codemagic Android keystore integration (preferred)
          if [ -n "${CM_KEYSTORE_PATH:-}" ] && [ -f "${CM_KEYSTORE_PATH:-}" ]; then
            KEYSTORE_PATH="${CM_KEYSTORE_PATH:-}"
          fi
          # Some setups expose CM_KEYSTORE_PATH as a directory. If so, locate the expected KEYSTORE_FILE inside.
          if [ -z "$KEYSTORE_PATH" ] && [ -n "${CM_KEYSTORE_PATH:-}" ] && [ -d "${CM_KEYSTORE_PATH:-}" ]; then
            echo "CM_KEYSTORE_PATH is a directory; listing:"
            ls -la "${CM_KEYSTORE_PATH:-}" || true
            if [ -n "${KEYSTORE_FILE:-}" ] && [ -f "${CM_KEYSTORE_PATH:-}/$KEYSTORE_FILE" ]; then
              KEYSTORE_PATH="${CM_KEYSTORE_PATH:-}/$KEYSTORE_FILE"
            else
              KEYSTORE_PATH="$(find "${CM_KEYSTORE_PATH:-}" -maxdepth 2 -type f -name '*.jks' 2>/dev/null | head -n 1 || true)"
            fi
          fi

          # 2) Secure files
          if [ -z "$KEYSTORE_PATH" ] && [ -n "${CM_SECURE_FILES_PATH:-}" ] && [ -f "${CM_SECURE_FILES_PATH:-}/$KEYSTORE_FILE" ]; then
            KEYSTORE_PATH="${CM_SECURE_FILES_PATH:-}/$KEYSTORE_FILE"
          fi

          # 3) Build dir (if user uploaded as a generic file)
          if [ -z "$KEYSTORE_PATH" ] && [ -f "$CM_BUILD_DIR/$KEYSTORE_FILE" ]; then
            KEYSTORE_PATH="$CM_BUILD_DIR/$KEYSTORE_FILE"
          fi

          if [ -z "$KEYSTORE_PATH" ] || [ ! -f "$KEYSTORE_PATH" ]; then
            echo "Keystore file not found for guardian."
            echo "Fix: Codemagic > Code signing identities > Android keystores"
            echo " - Add keystore reference name: guardian-upload"
            echo " - Upload file: guardian-upload.jks"
            echo " - Ensure this workflow attaches android_signing: guardian-upload"
            exit 2
          fi
          echo "KEYSTORE_PATH=$KEYSTORE_PATH"
          ls -la "$KEYSTORE_PATH" || true

          if [ -z "${CM_KEYSTORE_PASSWORD:-}" ]; then
            echo "Missing CM_KEYSTORE_PASSWORD. Set it via Codemagic keystore identity or env vars."
            exit 2
          fi

          # Auto-detect alias to avoid manual mistakes (works when keystore has a single entry).
          KEY_ALIAS="${CM_KEY_ALIAS:-}"
          if [ -z "$KEY_ALIAS" ]; then
            KEYTOOL_LIST="$(keytool -list -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" 2>&1)" || {
              echo "Failed to read keystore with CM_KEYSTORE_PASSWORD (wrong password?)"
              echo "$KEYTOOL_LIST" | head -n 20
              exit 8
            }
            KEY_ALIAS="$(echo "$KEYTOOL_LIST" | awk -F, 'NF>=1 {gsub(/^[ \t]+|[ \t]+$/, "", $1); if ($1!="" && $1!~/(Keystore type|Keystore provider)/) {print $1; exit}}')"
          fi
          if [ -z "$KEY_ALIAS" ]; then
            echo "Failed to detect key alias. Set CM_KEY_ALIAS explicitly."
            exit 2
          fi

          KEY_PASS="${CM_KEY_PASSWORD:-$CM_KEYSTORE_PASSWORD}"

          echo "=== SIGNING_INFO (guardian) ==="
          PKG="$(node -e \"console.log(require('../app.json').expo.android.package)\")"
          echo "package=$PKG"
          echo "versionCode=$(node -e \"console.log(require('../app.json').expo.android.versionCode)\")"
          echo "KEY_ALIAS=$KEY_ALIAS"
          CERT_INFO="$(keytool -list -v -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" -alias "$KEY_ALIAS" 2>&1)" || {
            echo "Failed to read cert details (wrong password/alias?)"
            echo "$CERT_INFO" | head -n 40
            exit 8
          }
          echo "$CERT_INFO" | grep -E "SHA1:|SHA256:" || true
          # Fail-fast guard: ensure we are signing with the upload certificate Play expects for guardian.
          if [ -n "${EXPECTED_UPLOAD_CERT_SHA1:-}" ]; then
            FOUND_SHA1="$(echo "$CERT_INFO" | grep -E "SHA1:" | head -n 1 | sed -E 's/.*SHA1:[[:space:]]*//')"
            if [ -z "$FOUND_SHA1" ]; then
              echo "FATAL: Could not determine signing cert SHA1 from keytool output."
              exit 9
            fi
            if [ "$FOUND_SHA1" != "$EXPECTED_UPLOAD_CERT_SHA1" ]; then
              echo "FATAL: Wrong signing cert for guardian."
              echo "found_sha1=$FOUND_SHA1"
              echo "expected_sha1=$EXPECTED_UPLOAD_CERT_SHA1"
              exit 9
            fi
          fi
          if command -v openssl >/dev/null 2>&1; then
            KEY_HASH="$(keytool -exportcert -alias "$KEY_ALIAS" -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" 2>/dev/null | openssl sha1 -binary | openssl base64 2>/dev/null || true)"
            if [ -n "$KEY_HASH" ]; then
              echo "KAKAO_KEY_HASH=$KEY_HASH"
              # Keep legacy single-line file for backwards-compat.
              echo "$KEY_HASH" > "$CM_BUILD_DIR/kakao_key_hash.txt"
              # Also write a traceable file to avoid confusion across builds/apps.
              SAFE_PKG="${PKG//./_}"
              OUT="$CM_BUILD_DIR/kakao_key_hash_${SAFE_PKG}_${CM_BUILD_NUMBER}.txt"
              {
                echo "package=$PKG"
                echo "build_number=${CM_BUILD_NUMBER:-}"
                echo "key_alias=$KEY_ALIAS"
                echo "kakao_key_hash_base64=$KEY_HASH"
              } > "$OUT"
            fi
          fi

          ./gradlew --no-daemon --max-workers=1 :app:bundleRelease \
            -Pandroid.injected.signing.store.file="$KEYSTORE_PATH" \
            -Pandroid.injected.signing.store.password="$CM_KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASS"
      - name: Verify + SHA256
        script: |
          cd "$APP_DIR/android"
          AAB="$(ls -1 app/build/outputs/bundle/release/*.aab | head -n 1 || true)"
          if [ -z "$AAB" ]; then
            echo "AAB not found"
            exit 3
          fi
          echo "AAB=$AAB"
          jarsigner -verify -verbose -certs "$AAB" || exit 4
          sha256sum "$AAB" | tee "$AAB.sha256.txt"
    artifacts:
      - kakao_key_hash.txt
      - kakao_key_hash_*.txt
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/bundle/release/*.sha256.txt
      - android/app/build/outputs/mapping/release/mapping.txt
      - android/app/build/reports/**/*
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

